name: Maire Grant
description: Writings about things
url: https://mairegrant.github.io/
highlighter: pygments

kramdown:
  input: GFM

permalink: /:title

timezone: America/New_York

include: [feed, .well-known/acme-challenge/RwAkBf87N7ypJlM4XUHIwO704mEkaYekOB3-iW2xSsQ]
